---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegate-webhook
  namespace: imagegate
  labels: &labels
    app: imagegate-webhook
    component: webhook
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
      name: imagegate-webhook
    spec:
      containers:
      - name: imagegate-webhook
        image: docker.io/dganochenko/imagegate:0.1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: "imagegate-webhook-config"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: certificates
          readOnly: true
          mountPath: "/app/certs"
      volumes:
      - name: certificates
        secret:
          secretName: imagegate-webhook-certificates
---
apiVersion: v1
kind: Service
metadata:
  name: imagegate-webhook
  namespace: imagegate
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: imagegate-webhook
    component: webhook

